import { defineCollection } from "astro:content";
import { docsSchema } from "@astrojs/starlight/schema";
import { glob } from "astro/loaders";

// The docs source lives in the repo-root `.articles/` directory (plain markdown, not tied to
// Astro), exposed here through the `src/content/docs` symlink. Starlight hardcodes that path
// when it resolves sidebar `autogenerate` directories and edit links, so pointing the loader
// straight at `../../.articles` leaves the autogenerated sidebar groups empty.
//
// Only the landing page and files inside numbered section folders are published, which
// deliberately excludes `.articles/README.md` (contributor notes, not a page). Numeric prefixes ("01-") are just
// for sorting on disk and are stripped from ids, so `.articles/02-guides/03-foo.md`
// is served at `/guides/foo/`; ordering comes from each file's `sidebar.order` frontmatter.
const stripNumericPrefix = (segment: string) => segment.replace(/^\d+-/, "");

export const collections = {
	docs: defineCollection({
		loader: glob({
			pattern: ["index.md", "[0-9]*/**/*.md"],
			base: "./src/content/docs",
			generateId: ({ entry }) =>
				entry.replace(/\.md$/, "").split("/").map(stripNumericPrefix).join("/"),
		}),
		schema: docsSchema(),
	}),
};
